### PR TITLE
Fix bugs in issue #471

### LINKED ISSUE #471: [Prusti internal error] generating fold-unfold Viper statements failed
Similarly to #447 (although with a different cause, I believe), Prusti reports an internal error in the following code:

```Rust
#[ensures(result == true ==> self.add_set.contains(&val))]
#[ensures(result == true ==> !self.remove_set.contains(&val))]
#[ensures(result == true ==> self.length() == old(self.length()) + 1)]
#[ensures(result == false ==> self.length() == old(self.length()))]
fn add(&mut self, val: u64) -> bool {
    if self.remove_set.contains(&val) {
        false
    }
    else {
        self.add_set.insert(val)
    }
}

#[ensures(result == true ==> self.remove_set.contains(&val))]
#[ensures(result == true ==> !self.add_set.contains(&val))]
#[ensures(result == true ==> self.length() == old(self.length()) + 1)]
#[ensures(result == false ==> self.length() == old(self.length()))]
fn remove(&mut self, val: u64) -> bool {
    if !self.add_set.contains(&val) {
        false
    }
    else {
        self.remove_set.insert(val)
    }
}

#[pure]
#[ensures(result ==> (self.add_set.contains(&val) && !self.remove_set.contains(&val)))]
#[ensures(!result ==> (!self.add_set.contains(&val) || self.remove_set.contains(&val)))]
fn contains(&self, val: u64) -> bool {
    self.add_set.contains(&val) && !self.remove_set.contains(&val)
}
```

More information about the error:

```Rust
error: [Prusti internal error] generating fold-unfold Viper statements failed (RequiresFolding("u64", [Local(_2: Ref(u64), Position { line: 36, column: 34, id: 169 })], Write, None, Position { line: 36, column: 34, id: 169 }))
  --> src/lib.rs:41:5
   |
41 | /     fn add(&mut self, val: u64) -> bool {
42 | |         if self.remove_set.contains(&val) {
43 | |             false
44 | |         }
...  |
47 | |         }
48 | |     }
   | |_____^

error: [Prusti internal error] generating fold-unfold Viper statements failed (RequiresFolding("u64", [Local(_2: Ref(u64), Position { line: 50, column: 34, id: 320 })], Write, None, Position { line: 50, column: 34, id: 320 }))
  --> src/lib.rs:54:5
   |
54 | /     fn remove(&mut self, val: u64) -> bool {
55 | |         if !self.add_set.contains(&val) {
56 | |             false
57 | |         }
...  |
60 | |         }
61 | |     }
   | |_____^

error: [Prusti internal error] generating unfolding Viper expressions failed (FailedToObtain(Pred(Local(_2: Ref(u64), Position { line: 70, column: 27, id: 351 }), read)))
  --> src/lib.rs:72:5
   |
72 | /     fn contains(&self, val: u64) -> bool {
73 | |         self.add_set.contains(&val) && !self.remove_set.contains(&val)
74 | |     }
   | |_____^
```

[Full code for this example](https://gist.github.com/jmc-figueira/9b0d5229662e15ca8358cdf6196eec90)
[Viper program dump](https://gist.github.com/jmc-figueira/b255fa700841aecc1d7372562c8f4032)

### PR DESCRIPTION
**Pull request by fpoli**
Closes #471

### CODE REVIEW

File: prusti-tests/tests/verify/pass/fold-unfold/cond-requirements.rs [hunk 1]
```diff
@@ -0,0 +1,35 @@
+//! From https://github.com/viperproject/prusti-dev/issues/471
+//! From https://github.com/viperproject/prusti-dev/issues/471
```
Comment (dario23) [inline prusti-tests/tests/verify/pass/fold-unfold/cond-requirements.rs]: duplicate line?
