### PR TITLE
Fix encoding of mutually recursive pure functions

### LINKED ISSUE #1267: Internal error from pure function calling itself in its contract
The following code produces an internal error in addition to the invalid specification error. It also marks `fn double(x: i64) -> i64` as the error source and not the `double(x)` call in the postcondition:
```
use prusti_contracts::*;

#[pure]
#[ensures(double(x) % 2 == 0)]
fn double(x: i64) -> i64 {
    2 * x
}
```
Produced error:
```
[Prusti: invalid specification] only trusted functions can call themselves in their contracts
[Prusti internal error] Prusti encountered an unexpected internal error
fn_calling_itself_in_specs.rs(5, 1): We would appreciate a bug report: https://github.com/viperproject/prusti-dev/issues/new
fn_calling_itself_in_specs.rs(5, 1): Details: Rust function m_uncategorized_problems$$fn_calling_itself_in_specs$$double encoded both as a Viper method and function
```

### PR DESCRIPTION
**Pull request by fpoli**
Use the `f_` prefix for encoding pure function names instead of `m_`.

Partially addresses #1214.
Fixes #1267.

### CODE REVIEW

**Comment by fpoli** [comment]
@vakaras The fix made the purification test `fail/core_proof/model2.rs` fail with 3 more errors of the kind "the termination measure of this call is not necessarily lower". I have no clue what caused them, so I [excluded](https://github.com/viperproject/prusti-dev/pull/1440/commits/3bc1d2079d2238131a924daa2bee797ae1319141) your encoder from this PR.

File: prusti-viper/src/encoder/mir/procedures/encoder/mod.rs [hunk 1]
```diff
@@ -1717,9 +1717,6 @@ impl<'p, 'v: 'p, 'tcx: 'v> ProcedureEncoder<'p, 'v, 'tcx> {
                 {
                     // If we are verifying a pure function, we always need
                     // to encode it as a method
-                    //
-                    // FIXME: This is not enough, we also need to handle
-                    // mutual-recursion case.
```
Comment (vakaras) [inline prusti-viper/src/encoder/mir/procedures/encoder/mod.rs:1722]: This should be kept because the soundness check is still missing.
