### PR TITLE
Small fixes

### LINKED ISSUE #878: Incorrect encoding of enum discriminant type
When encoding discriminants Prusti assumes that their type is `isize` (encoding [here](https://github.com/viperproject/prusti-dev/blob/7977d30a028edfe0e300bb2931992d4029385b41/prusti-viper/src/encoder/high/pure_functions/interface.rs#L59)), but this isn't always the case and so Prusti may panic due to the call on this [line](https://github.com/viperproject/prusti-dev/blob/7977d30a028edfe0e300bb2931992d4029385b41/prusti-viper/src/encoder/mir/pure/interpreter/mod.rs#L232) since the `encoded_lhs` has the correct type. An example which triggers this error is:
```rust
use prusti_contracts::*;
use std::cmp::{Ord, Ordering};

fn main() {}

#[extern_spec]
trait Ord {
    #[pure]
    fn cmp(&self, other: &Self) -> Ordering;
}

#[pure]
pub fn eq<T: Ord>(a: &T, b: &T) -> bool {
    match a.cmp(b) {
        Ordering::Equal => true,
        Ordering::Less => false,
        Ordering::Greater => false,
    }
}
```
Where:
```
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `Int(I8)`,
 right: `Int(Isize)`: _6 → discriminant(_3)', vir/src/../gen/vir_gen.rs:12610:25
```

### PR DESCRIPTION
**Pull request by JonasAlaif**
Kinda fixes #878 but would prefer if @vakaras looked at it/made it less hacky

### CODE REVIEW

File: prusti-viper/src/encoder/foldunfold/footprint.rs [hunk 1]
```diff
@@ -115,9 +115,6 @@ impl ExprFootprintGetter for vir::Expr {
                 box body,
                 ..
             }) => {
-                assert!(variables
```
Comment (Aurel300) [inline prusti-viper/src/encoder/foldunfold/footprint.rs:118]: Is this meant to be part of this PR? If we do this we should look into actually using the `is_quantifiable` function (there is a TODO somewhere in the code mentioning that).

**Review by vakaras — APPROVED** [review]
I am not sure about the removed `assert`s, but other changes look good to me.

File: prusti-viper/src/encoder/foldunfold/footprint.rs (hunk 1 above)
Comment (JonasAlaif) [reply prusti-viper/src/encoder/foldunfold/footprint.rs:118]: When I removed the same assert that you mentioned in https://github.com/viperproject/prusti-dev/issues/56#issuecomment-1046966018 I ended up running into this one causing a panic. Since it was the same one I had already removed (in [foldunfold/requirements.rs](https://github.com/viperproject/prusti-dev/blob/7977d30a028edfe0e300bb2931992d4029385b41/prusti-viper/src/encoder/foldunfold/requirements.rs#L328-L330)), I tried removing it here as well. @vakaras I agree that maybe we don't want to entirely remove the asserts, but just modify `!var.typ.is_typed_ref_or_type_var()` to `!var.typ.is_typed_ref()` or something?

Comment (vakaras) [reply prusti-viper/src/encoder/foldunfold/footprint.rs:118]: > @vakaras I agree that maybe we don't want to entirely remove the asserts, but just modify `!var.typ.is_typed_ref_or_type_var()` to `!var.typ.is_typed_ref()` or something?

Yes.

**Comment by JonasAlaif** [comment]
@vakaras if I convert this line:
https://github.com/viperproject/prusti-dev/blob/d53bdd7af1dda31d763e5fce83b2829aa1164a79/prusti-viper/src/encoder/mir/pure/specifications/encoder_poly.rs#L137
to:
```rust
let qvar_ty = encoder.encode_type(arg_ty).unwrap().convert_to_snapshot();
```
Quantification over generic types works... but I probably shouldn't use `convert_to_snapshot` here, but instead `SnapshotEncoder::encode_type`. The issue is that `fn encode_quantifier()` only gets a `encoder: &Encoder` and not `SnapshotEncoder` - is there any way to get the latter to this function?

**Comment by vakaras** [comment]
> @vakaras if I convert this line:
> 
> https://github.com/viperproject/prusti-dev/blob/d53bdd7af1dda31d763e5fce83b2829aa1164a79/prusti-viper/src/encoder/mir/pure/specifications/encoder_poly.rs#L137
> 
> to:
> 
> ```rust
> let qvar_ty = encoder.encode_type(arg_ty).unwrap().convert_to_snapshot();
> ```
> 
> Quantification over generic types works... but I probably shouldn't use `convert_to_snapshot` here, but instead `SnapshotEncoder::encode_type`. The issue is that `fn encode_quantifier()` only gets a `encoder: &Encoder` and not `SnapshotEncoder` - is there any way to get the latter to this function?

Isn't the snapshot encoder, a field of the `encoder`? Anyway, the code was written by @Aurel300, so he could probably tell more.

**Comment by Aurel300** [comment]
Yeah the snapshot encoder works with the usual interface trait + state mechanism now. So, if you import `crate::encoder::snapshot::SnapshotEncoderInterface`, you can call the [`encode_snapshot_type`](https://github.com/viperproject/prusti-dev/blob/d53bdd7af1dda31d763e5fce83b2829aa1164a79/prusti-viper/src/encoder/snapshot/interface.rs#L39) method on `Encoder`. It also takes a `SubstMap` (which should eventually be `SubstRef` maybe) so generics should get properly monomorphised at the callsite.

File: prusti-viper/src/encoder/foldunfold/footprint.rs (hunk 1 above)
Comment (JonasAlaif) [reply prusti-viper/src/encoder/foldunfold/footprint.rs:118]: Removed by [this recent commit](https://github.com/viperproject/prusti-dev/commit/07f7d6ce5fb96faadbbb58122ae5052778f44b3c#diff-464a6cfdb5cefcf2b9e5ae3d8b06fadd22f506153b31b3791230611df9671b8aL328-L330) so this is no longer an issue

**Comment by JonasAlaif** [comment]
Requires #895 now

**Comment by JonasAlaif** [comment]
Will merge this today or tomorrow if there are no objections? Though it's a small change it should actually improve generics support quite a bit

**Comment by Aurel300** [comment]
@JonasAlaif Can I try to get #899 in first?

**Comment by JonasAlaif** [comment]
@Aurel300 sounds good, looks like that might also fix some of the issues I might be running into with the test I just added. Let's see

**Comment by Aurel300** [comment]
Status: I found some problems with generics and extern specs still. WIP but I think the test you added @JonasAlaif should be supported soon.

(Some notes:)

The wrappers (from extern spec desugaring) are not inherited the same way that `is_pure` is. This can result in an annoying de-sync where an implementation (e.g. of `Ord`) is known to be pure but cannot be encoded because it would attempt to encode a non-local `DefId`. Extern spec wrappers should really disappear completely, and the `DefSpecificationMap` should have keys of `DefId` instead of only `LocalDefId`.

The reason the wrappers exist in the first place is because `PureFunctionEncoder` (and by extension the backwards interpreter and MIR encoder) are mis-used to encode call infos (`encode_pure_function_use`) and Prusti expressions (`encode_body`). I extracted the latter to a separate method and made fewer things in the `PureFunctionEncoder` depend on an MIR body to fix the former.
