### PR TITLE
Disambiguate between Generics in extern_spec rewriter

### LINKED ISSUE #626: Associated type bounds break external spec
The following code:
```rust
#![feature(associated_type_bounds)]
extern crate prusti_contracts;
use prusti_contracts::*;

#[extern_spec]
impl<T, D> Result<T, D> {
    #[pure]
    pub fn is_ok(&self) -> bool;
}

#[extern_spec]
impl<T, D: std::fmt::Debug> Result<T, D> {
    #[requires(self.is_ok())]
    pub fn unwrap(self) -> T;
}

fn main(){
  let ok: Result<i32, i32> = Ok(1);
  ok.unwrap();
}
```
results in an error:
```
error: associated type bounds are not allowed within structs, enums, or unions
  --> test2.rs:11:1
   |
11 | #[extern_spec]
   | ^^^^^^^^^^^^^^ in this macro invocation
   | 
  ::: /home/zgrannan/prusti-dev/prusti-contracts-internal/src/lib.rs:52:1
   |
52 | pub fn extern_spec(attr: TokenStream, tokens: TokenStream) -> TokenStream {
   | ------------------------------------------------------------------------- in this expansion of `#[extern_spec]`

```

The macro expansion is:
```rust
#![feature(prelude_import)]
#![no_std]
#![feature(associated_type_bounds)]



#![feature(register_tool)]
#![register_tool(prusti)]
#[prelude_import]
use ::std::prelude::rust_2015::*;
#[macro_use]
extern crate std;
extern crate prusti_contracts;
use prusti_contracts::*;
struct PrustiStructResultedc4f36317334af6bf6b75765220ce4e<T,
                                                          D>(std::marker::PhantomData<T>,
                                                             std::marker::PhantomData<D>);
impl <T, D> PrustiStructResultedc4f36317334af6bf6b75765220ce4e<T, D> {
    #[prusti::pure]
    #[prusti::trusted]
    #[prusti::extern_spec]
    pub fn is_ok(_self: &Result<T, D>) -> bool {
        Result::<T, D>::is_ok(_self);
        ::core::panicking::panic("not implemented")
    }
}
struct PrustiStructResultd427895dc1f144ed8ec027a3f5c578ad<T,
                                                          D: std::fmt::Debug>(std::marker::PhantomData<T>,
                                                                              std::marker::PhantomData<D
                                                                                                       : std::fmt::Debug>);
impl <T, D: std::fmt::Debug>
 PrustiStructResultd427895dc1f144ed8ec027a3f5c578ad<T, D : std::fmt::Debug> {
    #[allow(unused_must_use, unused_variables, dead_code)]
    #[prusti::spec_only]
    #[prusti::spec_id = "7cb61869cded43bcb896e1ad7477eb99"]
    #[prusti::assertion =
      "{\"kind\":{\"Expr\":{\"spec_id\":\"7cb61869-cded-43bc-b896-e1ad7477eb99\",\"expr_id\":101}}}"]
    fn prusti_pre_item_unwrap_7cb61869cded43bcb896e1ad7477eb99(_self:
                                                                   Result<T,
                                                                          D>) {

        #[prusti::spec_only]
        #[prusti::expr_id = "7cb61869cded43bcb896e1ad7477eb99_101"]
        || -> bool { _self.is_ok() };
    }
    #[prusti::pre_spec_id_ref = "7cb61869cded43bcb896e1ad7477eb99"]
    #[prusti::trusted]
    #[prusti::extern_spec]
    pub fn unwrap(_self: Result<T, D>) -> T {
        Result::<T, D>::unwrap(_self);
        ::core::panicking::panic("not implemented")
    }
}
fn main() { let ok: Result<i32, i32> = Ok(1); ok.unwrap(); }
```
It looks like the cause of the issue is that in the second external spec, the type bounds `std::fmt::Debug` are included after `D` is already in scope; they should be removed.

### PR DESCRIPTION
**Pull request by JonasAlaif**
Closes #626. The issue was caused by blindly using `syn::Generics` (generic _parameters_) as `syn::GenericArgument` (generic _arguments_).

### CODE REVIEW

File: prusti-specs/src/extern_spec_rewriter.rs [hunk 1]
```diff
@@ -226,18 +228,51 @@ pub fn generate_new_struct(item: &syn::ItemImpl) -> syn::Result<syn::ItemStruct>
...
 
     // Add `PhantomData` markers for each type parameter to silence errors
     // about unused type parameters.
     for param in generics.params.iter() {
-        let field = format!("core::marker::PhantomData<{}>,", param.to_token_stream().to_string());
-        fields_str.push_str(&field);
+        let field: ParsableUnnamedField = match param {
+            syn::GenericParam::Type(tp) => {
+                let ident = tp.ident.clone();
+                syn::parse_quote!{ core::marker::PhantomData<#ident> }
```
Comment (Aurel300) [inline prusti-specs/src/extern_spec_rewriter.rs]: Minor thing to prevent user-defined `core` imports or something…
```suggestion
                syn::parse_quote!{ ::core::marker::PhantomData<#ident> }
```
Also in L243.

File: prusti-specs/src/extern_spec_rewriter.rs [hunk 2]
```diff
@@ -205,6 +205,8 @@ fn rewrite_method_inputs(item_ty: &syn::Type, method: &mut ImplItemMethod) ->
     args
 }
 
+type CommaPunct<T> = syn::punctuated::Punctuated<T, syn::token::Comma>;
```
Comment (Aurel300) [inline prusti-specs/src/extern_spec_rewriter.rs]:
```suggestion
type CommaPunct<T> = syn::punctuated::Punctuated<T, syn::Token![,]>;
```

File: prusti-specs/src/extern_spec_rewriter.rs [hunk 3]
```diff
@@ -226,18 +228,51 @@ pub fn generate_new_struct(item: &syn::ItemImpl) -> syn::Result<syn::ItemStruct>
...
+        };
+        // Unwrap the `ParsableUnnamedField` and push. See below.
+        fields.push(field.0);
     }
 
-    let fields : syn::FieldsUnnamed =
-        syn::parse_str(&format!("({})", fields_str)).unwrap();
-
-    new_struct.fields = syn::Fields::Unnamed(fields);
+    new_struct.fields = syn::Fields::Unnamed( syn::parse_quote!{ (#fields) } );
```
Comment (Aurel300) [inline prusti-specs/src/extern_spec_rewriter.rs]: Does it work if you define `fields` as a `Vec<syn::Field>` and then:
```suggestion
    new_struct.fields = syn::Fields::Unnamed( syn::parse_quote!{ (#(#fields),*) } );
```
If so, you can get rid of the `CommaPunct` bit, and just have `let mut fields = vec![];`

File: prusti-specs/src/extern_spec_rewriter.rs [hunk 4]
```diff
@@ -226,18 +228,51 @@ pub fn generate_new_struct(item: &syn::ItemImpl) -> syn::Result<syn::ItemStruct>
...
+pub fn rewrite_generics(gens: &syn::Generics) -> syn::AngleBracketedGenericArguments {
+    let args: CommaPunct::<syn::GenericArgument> = gens.params.clone().iter().map(|gp| {
+        let ts = match gp {
+            syn::GenericParam::Type(syn::TypeParam { ident, .. }) |
+            syn::GenericParam::Const(syn::ConstParam { ident, .. }) => ident.into_token_stream(),
+            syn::GenericParam::Lifetime(ld) => ld.lifetime.clone().into_token_stream(),
+        };
+        let res: syn::GenericArgument = syn::parse_quote!{#ts}; res
+    }).collect();
+    syn::parse_quote!{ < #args > }
```
Comment (Aurel300) [inline prusti-specs/src/extern_spec_rewriter.rs]: (Same comment as above about `Vec`)

File: prusti-specs/src/extern_spec_rewriter.rs [hunk 5]
```diff
@@ -226,18 +228,51 @@ pub fn generate_new_struct(item: &syn::ItemImpl) -> syn::Result<syn::ItemStruct>
...
+/// but then need to pass those as arguments: `SomeStruct<...>`. This function translates from
+/// the syntax of one to the other; e.g. `<T: Bound, 'l: Bound, const C: usize>` -> `<T, 'l, C>`
+pub fn rewrite_generics(gens: &syn::Generics) -> syn::AngleBracketedGenericArguments {
+    let args: CommaPunct::<syn::GenericArgument> = gens.params.clone().iter().map(|gp| {
+        let ts = match gp {
+            syn::GenericParam::Type(syn::TypeParam { ident, .. }) |
+            syn::GenericParam::Const(syn::ConstParam { ident, .. }) => ident.into_token_stream(),
+            syn::GenericParam::Lifetime(ld) => ld.lifetime.clone().into_token_stream(),
+        };
+        let res: syn::GenericArgument = syn::parse_quote!{#ts}; res
```
Comment (Aurel300) [inline prusti-specs/src/extern_spec_rewriter.rs]: A `syn::parse_quote!{ #ts }` should be equivalent to `syn::parse(ts)` (or `parse2` depending on which type it is).
```suggestion
        syn::parse::<syn::GenericArgument>(ts).unwrap()
```

**Review by Aurel300 — CHANGES_REQUESTED** [review]
Looks good! Small improvements might be possible, and more importantly: please add a test.

File: prusti-specs/src/extern_spec_rewriter.rs (hunk 3 above)
Comment (JonasAlaif) [reply prusti-specs/src/extern_spec_rewriter.rs]: Hmm do you think it's more clear like you suggest? I could just import `syn::punctuated::Punctuated` and use `Punctuated<syn::Field, syn::Token![,]>` as the type of `fields` - that way we also do not need the type alias, but avoid this `parse_quote` black magic?

Comment (Aurel300) [reply prusti-specs/src/extern_spec_rewriter.rs]: Sure, both save space a bit. I think this type of interpolation is used in other places already, so it wouldn't be too out of place :)

File: prusti-specs/src/extern_spec_rewriter.rs [hunk 6]
```diff
@@ -228,27 +226,27 @@ pub fn generate_new_struct(item: &syn::ItemImpl) -> syn::Result<syn::ItemStruct>
     new_struct.generics = item.generics.clone();
     let generics = &new_struct.generics;
 
-    let mut fields = CommaPunct::<syn::Field>::new();
+    let mut fields = Vec::<syn::Field>::new();
```
Comment (Aurel300) [inline prusti-specs/src/extern_spec_rewriter.rs]:
```suggestion
    let mut fields = vec![];
```

File: prusti-tests/tests/verify/pass/extern-spec/trait-bounds.rs [hunk 7]
```diff
@@ -0,0 +1,18 @@
+// ignore-test None of this Generics stuff currently works with Prusti...
```
Comment (Aurel300) [inline prusti-tests/tests/verify/pass/extern-spec/trait-bounds.rs:1]: Ok, could we then have a UI test as well? :D
